# Generated by Django 6.0.2 on 2026-02-05 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='dead_line',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='campaign',
            old_name='User',
            new_name='owner',
        ),
    ]
